# irreps_in: '64x0e'
# irreps_node_embedding: '64x0e+64x1o+64x2e+64x3o+64x4e+64x5o+64x6e'
# num_layers: 6
# irreps_node_attr: '1x0e'
# irreps_sh: '1x0e+1x1o+1x2e+1x3o+1x4e+1x5o+1x6e'
# max_radius: 15
# number_of_basis: 8
# fc_neurons: [64, 64]
# basis_type: 'bessel'
# irreps_feature: '512x0e'
# irreps_head: '32x0e+16x1o+8x2e+8x3o+8x4e+8x5o+8x6e'
# num_heads: 4
# irreps_pre_attn: null
# rescale_degree: false
# nonlinear_message: true
# irreps_mlp_mid: '384x0e+192x1o+96x2e+96x3o+48x4e+48x5o+48x6e'
# norm_layer: 'layer'
# alpha_drop: 0.0
# proj_drop: 0.0
# out_drop: 0.0
# drop_path_rate: 0.0
# mean: null
# std: null
# scale: null
# atomref: null
# return_dic: True
# enable_hami: True
# embedding_dimension: 64
# bottle_hidden_size: 32
# radius_embed_dim: 8
# order: 6
# load_pretrain: ''
irreps_in: '64x0e'
irreps_node_embedding: '64x0e+64x1e+64x2e+64x3e'
num_layers: 6
irreps_node_attr: '1x0e'
irreps_sh: '1x0e+1x1e+1x2e+1x3e'
max_radius: 5
number_of_basis: 8
fc_neurons: [64, 64]
basis_type: 'bessel'
irreps_feature: '512x0e'
irreps_head: '32x0e+16x1e+8x2e+8x3e'
num_heads: 4
irreps_pre_attn: null
rescale_degree: false
nonlinear_message: true
irreps_mlp_mid: '384x0e+192x1e+96x2e+96x3e'
norm_layer: 'layer'
alpha_drop: 0.0
proj_drop: 0.0
out_drop: 0.0
drop_path_rate: 0.0
mean: null
std: null
scale: null
atomref: null
return_dic: True
enable_hami: True
embedding_dimension: 64
bottle_hidden_size: 32
order: 6
load_pretrain: ''
increase_order: True