regress_forces: True
hidden_channels: 128
num_layers: 6
num_rbf: 50
rbf_type: "expnorm"
trainable_rbf: True
activation: "silu"
attn_activation: "silu"
neighbor_embedding: True
num_heads: 8
distance_influence: "both"
short_cutoff_lower: 0
short_cutoff_upper: 10
long_cutoff_lower: 0
long_cutoff_upper: 10
mean: null
std: null
atom_ref: null
max_z: 100
max_num_neighbors: 32
group_center: 'center_of_mass'
tf_writer: null
long_num_layers: 2
dropout: 0
energy_force: True
load_pretrain: ''